import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { PCP_CONTRACT } from "./contract.js";
import { JsonRpcRequestSchema, JsonRpcResponseSchema } from "./jsonrpc.js";
import { AppClientSchema } from "./schemas/app-client.js";
import {
  ConsentAccessPolicySchema,
  PcpAuthorizationBindingResultSchema,
  PcpAuthorizationCodeExchangeSchema,
  PcpAuthorizationDiscoverySchema,
  PcpAuthorizationRequestSchema
} from "./schemas/authorization-consent.js";
import { AuditLogSchema } from "./schemas/audit-log.js";
import { ConsentGrantSchema } from "./schemas/consent-grant.js";
import { ContextItemSchema } from "./schemas/context-item.js";
import { ContextPackSchema } from "./schemas/context-pack.js";
import {
  InitializeParamsSchema,
  InitializeResultSchema
} from "./schemas/initialize.js";
import { MemoryProposalSchema } from "./schemas/memory-proposal.js";
import {
  AuditListParamsSchema,
  AuditListResultSchema,
  ConsentListParamsSchema,
  ConsentListResultSchema,
  ConsentRevokeParamsSchema,
  ConsentRevokeResultSchema,
  ContextRequestParamsSchema,
  ContextRequestResultSchema,
  ContextSearchParamsSchema,
  ContextSearchResultSchema,
  ExportCreateParamsSchema,
  ExportCreateResultSchema,
  MemoryCreateParamsSchema,
  MemoryCreateResultSchema,
  MemoryDeleteParamsSchema,
  MemoryDeleteResultSchema,
  MemoryProposeParamsSchema,
  MemoryProposeResultSchema
} from "./schemas/methods.js";

const PcpV01Schema = z.object({
  jsonRpcRequest: JsonRpcRequestSchema,
  jsonRpcResponse: JsonRpcResponseSchema,
  objects: z.object({
    appClient: AppClientSchema,
    consentGrant: ConsentGrantSchema,
    contextItem: ContextItemSchema,
    contextPack: ContextPackSchema,
    memoryProposal: MemoryProposalSchema,
    auditLog: AuditLogSchema
  }),
  profiles: z.object({
    authorizationConsent: z.object({
      authorizationRequest: PcpAuthorizationRequestSchema,
      authorizationCodeExchange: PcpAuthorizationCodeExchangeSchema,
      authorizationBindingResult: PcpAuthorizationBindingResultSchema,
      authorizationDiscovery: PcpAuthorizationDiscoverySchema,
      consentAccessPolicy: ConsentAccessPolicySchema
    })
  }),
  methods: z.object({
    initialize: z.object({
      params: InitializeParamsSchema,
      result: InitializeResultSchema
    }),
    contextRequest: z.object({
      params: ContextRequestParamsSchema,
      result: ContextRequestResultSchema
    }),
    contextSearch: z.object({
      params: ContextSearchParamsSchema,
      result: ContextSearchResultSchema
    }),
    memoryPropose: z.object({
      params: MemoryProposeParamsSchema,
      result: MemoryProposeResultSchema
    }),
    memoryCreate: z.object({
      params: MemoryCreateParamsSchema,
      result: MemoryCreateResultSchema
    }),
    memoryDelete: z.object({
      params: MemoryDeleteParamsSchema,
      result: MemoryDeleteResultSchema
    }),
    consentList: z.object({
      params: ConsentListParamsSchema,
      result: ConsentListResultSchema
    }),
    consentRevoke: z.object({
      params: ConsentRevokeParamsSchema,
      result: ConsentRevokeResultSchema
    }),
    auditList: z.object({
      params: AuditListParamsSchema,
      result: AuditListResultSchema
    }),
    exportCreate: z.object({
      params: ExportCreateParamsSchema,
      result: ExportCreateResultSchema
    })
  })
});

const outputPath = resolve("schemas/pcp-v0.1.schema.json");
const contractOutputPath = resolve("schemas/pcp-v0.1.contract.json");
const rustContractOutputPath = resolve(
  "../../sdk/rust/pcp-sdk/src/generated_contract.rs"
);
const jsonSchema = zodToJsonSchema(PcpV01Schema, {
  name: "PcpV01",
  target: "jsonSchema7"
});

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${JSON.stringify(jsonSchema, null, 2)}\n`);
await writeFile(contractOutputPath, `${JSON.stringify(PCP_CONTRACT, null, 2)}\n`);
await mkdir(dirname(rustContractOutputPath), { recursive: true });
await writeFile(rustContractOutputPath, renderRustContractModule());

function renderRustContractModule(): string {
  const methods = PCP_CONTRACT.methods;
  const authScheme = PCP_CONTRACT.auth.schemes[0];
  if (!authScheme) {
    throw new Error("PCP contract must define at least one auth scheme");
  }

  return `// Generated by packages/protocol/src/generate-json-schema.ts.
// Do not edit by hand.

pub const PCP_CONTRACT_ID: &str = "${PCP_CONTRACT.id}";
pub const PCP_PROTOCOL_VERSION: &str = "${PCP_CONTRACT.protocolVersion}";
pub const PCP_JSON_RPC_VERSION: &str = "${PCP_CONTRACT.envelope.jsonrpc}";
pub const PCP_HTTP_JSON_RPC_METHOD: &str = "${PCP_CONTRACT.transport.method}";
pub const PCP_BEARER_AUTH_SCHEME: &str = "${authScheme}";
pub const PCP_SERVER_INFO_NAME: &str = "${PCP_CONTRACT.referenceServer.info.name}";
pub const PCP_SERVER_INFO_VERSION: &str = "${PCP_CONTRACT.referenceServer.info.version}";
pub const PCP_SERVER_INFO_DESCRIPTION: &str = "${PCP_CONTRACT.referenceServer.info.description}";
pub const PCP_SERVER_INSTRUCTIONS: &str = "${PCP_CONTRACT.referenceServer.instructions}";

pub const PCP_METHOD_INITIALIZE: &str = "${methods.initialize}";
pub const PCP_METHOD_CONTEXT_REQUEST: &str = "${methods.contextRequest}";
pub const PCP_METHOD_CONTEXT_SEARCH: &str = "${methods.contextSearch}";
pub const PCP_METHOD_MEMORY_PROPOSE: &str = "${methods.memoryPropose}";
pub const PCP_METHOD_MEMORY_CREATE: &str = "${methods.memoryCreate}";
pub const PCP_METHOD_MEMORY_DELETE: &str = "${methods.memoryDelete}";
pub const PCP_METHOD_CONSENT_LIST: &str = "${methods.consentList}";
pub const PCP_METHOD_CONSENT_REVOKE: &str = "${methods.consentRevoke}";
pub const PCP_METHOD_AUDIT_LIST: &str = "${methods.auditList}";
pub const PCP_METHOD_EXPORT_CREATE: &str = "${methods.exportCreate}";
`;
}
