// Generated by packages/protocol/src/generate-json-schema.ts.
// Do not edit by hand.

pub const PCP_CONTRACT_ID: &str = "pcp.v0.1";
pub const PCP_PROTOCOL_VERSION: &str = "2026-06-24";
pub const PCP_JSON_RPC_VERSION: &str = "2.0";
pub const PCP_HTTP_JSON_RPC_METHOD: &str = "POST";
pub const PCP_BEARER_AUTH_SCHEME: &str = "Bearer";

pub const PCP_METHOD_INITIALIZE: &str = "initialize";
pub const PCP_METHOD_CONTEXT_REQUEST: &str = "pcp.context.request";
pub const PCP_METHOD_CONTEXT_SEARCH: &str = "pcp.context.search";
pub const PCP_METHOD_MEMORY_PROPOSE: &str = "pcp.memory.propose";
pub const PCP_METHOD_MEMORY_CREATE: &str = "pcp.memory.create";
pub const PCP_METHOD_MEMORY_DELETE: &str = "pcp.memory.delete";
pub const PCP_METHOD_CONSENT_LIST: &str = "pcp.consent.list";
pub const PCP_METHOD_CONSENT_REVOKE: &str = "pcp.consent.revoke";
pub const PCP_METHOD_AUDIT_LIST: &str = "pcp.audit.list";
pub const PCP_METHOD_EXPORT_CREATE: &str = "pcp.export.create";
